Repository sensuikan1973/HumanLifeGame, pull requests merged in 2020-04, with the labels that each got.

#5 add CI
  .github/workflows/flutter_analyzer.yaml
  .github/workflows/flutter_build.yaml
  .github/workflows/flutter_format.yaml
  .github/workflows/flutter_test.yaml
  README.md
Labels: GitHubActions

#8 Codecov
  .codecov.yml
  .github/workflows/flutter_test.yaml
  README.md
Labels: Codecov

#16 add i18n
  .codecov.yml
  .vscode/launch.json
  README.md
  analysis_options.yaml
  lib/domain/play_room/player_action.dart
  lib/human_life_game_app.dart
  lib/i18n/create_arb.sh
  lib/i18n/create_message_class.sh
  lib/i18n/i18n.dart
  lib/i18n/i18n_delegate.dart
  lib/i18n/intl_en.arb
  lib/i18n/intl_ja.arb
  lib/i18n/intl_messages.arb
  lib/i18n/messages_all.dart
  lib/i18n/messages_en.dart
  lib/i18n/messages_ja.dart
  lib/i18n/messages_messages.dart
  pubspec.lock
  pubspec.yaml
  test/widget/player_action_test.dart
Labels: Codecov, i18n

#17 add comment for analysis_options exclude option
  analysis_options.yaml
Labels: i18n

#24 auto Assignee on PR
  .github/auto_assign.yaml
  .github/workflows/pr_auto_assign.yaml
Labels: GitHubActions

#20 add lacked localizationsDelegates
  lib/human_life_game_app.dart
Labels: i18n

#21 add app title
  lib/human_life_game_app.dart
  lib/i18n/i18n.dart
  lib/i18n/intl_en.arb
  lib/i18n/intl_ja.arb
  lib/i18n/intl_messages.arb
  lib/i18n/messages_en.dart
  lib/i18n/messages_ja.dart
  lib/i18n/messages_messages.dart
Labels: i18n
