Repository sensuikan1973/HumanLifeGame, pull requests merged in 2020-05, with the labels that each got.

#42 ass widget test helper
  lib/i18n/create_arb.sh
  lib/i18n/create_message_class.sh
  lib/i18n/intl_en.arb
  lib/i18n/intl_ja.arb
  lib/i18n/intl_messages.arb
  lib/i18n/messages_en.dart
  lib/i18n/messages_ja.dart
  lib/i18n/messages_messages.dart
  test/unit/sample_test.dart
  test/widget/dice_result_test.dart
  test/widget/helper/widget_build_helper.dart
  test/widget/human_life_stages_test.dart
  test/widget/play_room_test.dart
  test/widget/player_action_test.dart
Labels: i18n

#46 roll announcement i18n
  lib/i18n/extensions/i18n_common.dart
  lib/i18n/extensions/i18n_play_room.dart
  lib/i18n/intl_en.arb
  lib/i18n/intl_ja.arb
  lib/i18n/intl_messages.arb
  lib/i18n/messages_en.dart
  lib/i18n/messages_ja.dart
  lib/i18n/messages_messages.dart
  lib/models/play_room.dart
  lib/screens/play_room/play_room.dart
  test/widget/play_room_test.dart
Labels: i18n

#47 set defaultLocale when I18n.load
  lib/i18n/i18n.dart
Labels: i18n

#56 fix class typo and import order
  lib/human_life_game_app.dart
  lib/i18n/create_message_class.sh
  lib/i18n/extensions/i18n_play_room.dart
  lib/i18n/intl_en.arb
  lib/i18n/intl_ja.arb
  lib/i18n/intl_messages.arb
  lib/i18n/messages_en.dart
  lib/i18n/messages_ja.dart
  lib/i18n/messages_messages.dart
  lib/screens/play_room/life_event_records.dart
  lib/screens/play_room/play_room.dart
  test/widget/life_event_recodes_test.dart
Labels: i18n

#58 temporary turn system
  lib/i18n/extensions/i18n_play_room.dart
  lib/i18n/intl_en.arb
  lib/i18n/intl_ja.arb
  lib/i18n/intl_messages.arb
  lib/i18n/messages_en.dart
  lib/i18n/messages_ja.dart
  lib/i18n/messages_messages.dart
  lib/models/play_room/play_room.dart
  test/widget/play_room_test.dart
Labels: i18n

#85 Update provider package and Workaround for flutter action
  .github/workflows/flutter_analyzer.yaml
  .github/workflows/flutter_build.yaml
  .github/workflows/flutter_test.yaml
  pubspec.lock
  pubspec.yaml
Labels: GitHubActions

#83 define GainLifeItemParams
  .github/workflows/flutter_analyzer.yaml
  .github/workflows/flutter_test.yaml
  .gitignore
  README.md
  analysis_options.yaml
  lib/models/common/life_event_doc.md
  lib/models/common/life_event_params/gain_life_item_params.dart
  lib/models/common/life_event_params/target_life_item_params.dart
  lib/models/common/life_road.dart
  lib/screens/play_room/play_room.dart
  pubspec.lock
  pubspec.yaml
  test/unit/models/gain_life_item_params_test.dart
Labels: GitHubActions

#93 deploy firebase hosting
  .firebaserc
  .github/workflows/flutter_analyzer.yaml
  .github/workflows/flutter_build.yaml
  .github/workflows/flutter_test.yaml
  .github/workflows/flutter_web_deploy.yaml
  .gitignore
  README.md
  firebase.json
  web/index.html
Labels: Firebase Hosting, GitHubActions, HTML

#111 first Implement for Authentication
  .gitignore
  .idea/runConfigurations/main_dart.xml
  .vscode/launch.json
  README.md
  firebase.json
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  lib/router.dart
  lib/screens/sign_in/sign_in.dart
  pubspec.lock
  pubspec.yaml
  web/index.html
  web/init_firebase.js
Labels: Firebase Authentication, Firebase Hosting

#123 fix redirect url of sign in
  lib/screens/sign_in/sign_in.dart
  pubspec.lock
  pubspec.yaml
Labels: Firebase Authentication

#125 add update_dependencies job
  .github/workflows/update_dependencies.yaml
Labels: GitHubActions

#134 Hosting Dart Document on GitHub Page
  .github/workflows/flutter_analyzer.yaml
  .github/workflows/flutter_build.yaml
  .github/workflows/flutter_format.yaml
  .github/workflows/flutter_test.yaml
  .github/workflows/flutter_web_deploy.yaml
  .github/workflows/upload_dart_docs.yaml
  .gitignore
  README.md
Labels: GitHubActions

#137 update firebase deploy DEV status
  .github/workflows/flutter_web_deploy.yaml
Labels: Firebase Hosting, GitHubActions

#139 add lobby page
  lib/api/auth.dart
  lib/router.dart
  lib/screens/lobby/lobby.dart
  test/widget/human_life_game_app_test.dart
  web/init_firebase.js
Labels: Firebase Authentication

#141 first implement Auth
  .github/workflows/flutter_analyzer.yaml
  .github/workflows/flutter_build.yaml
  .gitignore
  README.md
  config/.env.sample
  lib/api/auth.dart
  lib/main.dart
  lib/models/common/life_item.dart
  lib/screens/lobby/lobby.dart
  pubspec.lock
  pubspec.yaml
Labels: Firebase Authentication

#143 fix Web_Deploy action
  .github/workflows/flutter_web_deploy.yaml
  lib/main.dart
Labels: GitHubActions

#144 add script for github actions
  .github/workflows/flutter_analyzer.yaml
  .github/workflows/flutter_build.yaml
  .github/workflows/flutter_test.yaml
  .github/workflows/flutter_web_deploy.yaml
  scripts/setup_flutter_web.sh
Labels: GitHubActions

#146 update jobs
  .github/workflows/update_dependencies.yaml
  .github/workflows/upload_dart_docs.yaml
Labels: GitHubActions

#148 fix deploy job
  .github/workflows/flutter_web_deploy.yaml
Labels: Firebase Hosting, GitHubActions

#149 Play view image
  images/2.0x/play_view_background.jpg
  images/3.0x/play_view_background.jpg
  images/play_view_background.jpg
  lib/screens/play_room/play_view.dart
  pubspec.yaml
Labels: Asset

#154 use cloud_firstore_mocks & add test
  lib/api/firestore/service_control.dart
  pubspec.lock
  pubspec.yaml
  test/widget/maintenance_test.dart
Labels: Firestore

#155 add vscode launch setting with firestore emulator
  .vscode/launch.json
Labels: Firestore

#157 change fetching firebase init json on dev
  README.md
  firebase.json
  web/init_firebase.js
Labels: Firebase Hosting
